### ISSUE TITLE
HiWi - Eingabemaske für Stundenzettel erstellen // 5P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#22]
Als HiWi möchte ich meine Arbeitsstunden für den monatlichen Stundenzettel festhalten können. 

In meinem Profil sehe ich dafür unter "Arbeitsstunden" Links zu den jeweiligen Monaten. Der erste Monat, der aufgeführt ist, ist der aktuelle Monat. Der letzte Monate ist derjenige, in dem ich mich beim Wimi Portal registriert habe. Der Link zu einem Monat führt auf eine neue Seite. Hier werden alle Arbeitsstunden, die zu diesem Monat gehören, gruppiert aufgeführt. Ich kann Arbeitsstunden hinzufügen, editieren und löschen. Außerdem kann ich alle Arbeitsstunden eines Monats als PDF exportieren (bzw. sehe ich einen Button dafür).

**Tasks**
- [ ] Views für einzelne Monate erstellen (8h)
- [ ] Profilview anpassen (2h) 
- [ ] Migration (Tabelle für Arbeitsstunden)  (30min) 
- [ ] funktionslosen "PDF erstellen" Button erstellen (30min) 

**Akzeptanzkriterien**
- [ ] Auf meinem Profil gibt es unter "Arbeitsstunden" einen Link zu einer neuen View, die meine Arbeitsstunden für den aktuellen Monat anzeigt.
- [ ] Auf der Seite für einen bestimmten Monat gibt es einen Button, um neue Arbeitsstunden hinzuzufügen.
- [ ] Füge ich neue Arbeitsstunden hinzu, gibt es Felder für Tag/Datum, Start- und Endzeit, Pausenzeit, Status bzw. "*" (optionale Auswahl: Urlaubstag, Krank, Feiertag) Anmerkungen.
- [ ] Auf der Seite, auf der die Arbeitsstunden zu einem Monat zusammengefasst werden, gibt einen Knopf 'Als PDF exportieren'.

![bildschirmfoto 2015-11-12 um 09 46 06](https://cloud.githubusercontent.com/assets/7271491/11114152/c0291050-8922-11e5-9231-b42ad105e50c.png)

![bildschirmfoto 2015-11-12 um 09 48 27](https://cloud.githubusercontent.com/assets/7271491/11114161/c76ddcec-8922-11e5-9b0c-34f04658c8f4.png)

**Comment by bahnfahren** [comment]
#18

**Comment by bahnfahren** [comment]
Bei '*' soll ja die optionale Auswahl für 'Sick' etc hin, jetzt ist nur die Frage, ob das wirklich wie in dem Bild mit einem char Eintrag gelöst wird - wobei sprachrelatierte Probleme auftauchen werden (S für Sick oder K für Krank?) - oder ob man checkboxes für jeweils 'Sick' und so gibt. Was meinst du @mandyklingbeil ?

**Comment by mandyklingbeil** [comment]
@bahnfahren: Bitte immer bedenken, dass die Formulare immer auf Deutsch sind, da wir an einem deutschen Institut sind. Das heißt, dass die daraus resultierende PDF auf Deutsch sein wird. Schau dir am besten Mal kurz das Excel-Sheet für den Stundenzettel an, das ich über Slack geteilt hatte. Dort gibt es eine Legende für "K" (Krank) und "F" (Feiertag). Urlaub ist dort zwar nicht aufgeführt, sollte aber als "U" passen (die Personalabteilung hat bei mir nie gemeckert). Sollte jemand, der das System auf Englisch benutzt, die Daten eingeben, dann sollte er natürlich "sick" etc. lesen, aber im Formular tauchen später die deutschen Abkürzungen auf.
