### ISSUE TITLE
Administrator - Rolle//13P

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#32]
Als 'Administrator' bin ich immer einem Lehrstuhl zugeordnet (siehe auch #25).
Als 'Administrator' bin ich der erste User eines Lehrstuhls. Als solcher bin ich dafür zuständig HiWi anfragen zu dem Lehrstuhl zu bestätigen oder abzulehnen (siehe auch #7)
Als 'Administrator' habe ich alle Rechte, die ein 'WiMi' des Lehrstuhls hat.

Zusätzlich (Dies dient nur der Rollenbeschreibung, ist aber erstmal nicht wichtig für diese User-Story):
+ können alle Projekte verwaltet werden
+ können User des Lehrstuhls verwaltet werden (HiWi,WiMi, Projektzuordnung)

**Akzeptanzkriterien**
- [x] Als 'Administrator' bin ich immer genau einem Lehrstuhl zugeordnet
- [x] Als Administrator kann ich die Tätigkeiten auch nur auf diesem Lehrstuhl ausüben
- [x] Kann 'WiMi' Anfragen an den Lehrstuhl einsehen
- [x] Kann 'WiMi' Anfragen annehmen oder ablehnen und sieht diese Anfragen dann nicht mehr
- [x] Wenn eine Anfrage angenommen wird, so ist der angenommene 'User' ein 'WiMi' des Lehrstuhls

**Tasks**
- [x] 'chair_wimi' Admin Attribut hinzufügen. 
- [x] View für Admins / FG-Beauftragte erstellen, ... siehe #5 
- [x] Tests aus altem Branch in neuen reinmergen

**Comment by marcelja** [comment]
@swt-r0ckz und ich machen das
