### ISSUE TITLE
Dashboard - WiMi-Aktionen anzeigen

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#36]
Als WiMi möchte ich auf meinem Dashboard Links zu folgenden Aktionen angezeigt bekommen, um diese häufig wiederkehrenden Tätigkeiten schnell durchzuführen:

**Akzeptanzkritieren**
- [ ] Urlaub beantragen (verlinkt zum Formular #13)
- [ ] Dienstreise beantragen (verlinkt zum Formular #14)
- [ ] Reisekosten abrechnen (verlinkt zum Formular #16)

![capture](https://cloud.githubusercontent.com/assets/9438971/11625645/cd214188-9cdc-11e5-96ea-71fe9844c5fb.PNG)
