### ISSUE TITLE
Wimi - Dashboard

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#37]
Als 'WiMi' möchte ich über sämtliche Aktivitäten, die mich betreffen, eine Benachrichtigung auf meinem Dashboard bekommen.

**Atomic Tasks**
- [x] Layout anlegen
- [x] Aktions Box erstellen
- [x] Projekte Box erstellen
- [x] Notification für Stundenzettel eingereicht
- [x] Notification für Dienstreiseantrag angenommen
- [x] Notification für Dienstreiseantrag abgelehnt
- [x] Notifications Anzeigen

**Akzeptanzkriterien**
- [ ] Ich erhalte eine Benachrichtigung, wenn ein 'HiWi' eines meiner Projekts ein Stundenzettel eingereicht hat
- [ ] Ich erhalte eine Benachrichtigung, wenn ein von mir eingereichter Antrag bestätigt wurde und kann diesen dann direkt einsehen
- [ ] Ich erhalte eine Benachrichtigung, wenn ein von mir eingereichter Antrag abgelehnt wurde und kann diesen dann direkt einsehen
- [ ] Projekt erstellen (verlinkt auf die Seite zum Anlegen neuer Projekte #9)
- [ ] Urlaub beantragen (verlinkt zum Formular #13)
- [ ] Dienstreise beantragen (verlinkt zum Formular #14)
- [ ] Reisekosten abrechnen (verlinkt zum Formular #16)
- [ ] Es gibt einen Bereich in dem meine Projekte angezeigt und verlinkt werden

![capture](https://cloud.githubusercontent.com/assets/9438971/11838294/5e80c3dc-a3e6-11e5-8642-c125e686b0e8.PNG)

**Comment by sleighsoft** [comment]
Folgendes Akzeptanzkriterium ergänzt
- Projekt erstellen (verlinkt auf die Seite zum Anlegen neuer Projekte #9)

Damit wird Userstory #39 obsolete.

**Comment by mandyklingbeil** [comment]
Ggf. "Projekt erstellen" bei WiMi-Aktionen ganz nach unten auf der Liste setzen oder aber z.B. ein Plus-Sign-Glyphicon neben "Meine Projekte" setzen, das auf die entsprechende Seite zum Erstellen eines neuen Projektes verlinkt.
