### ISSUE TITLE
FG-Beauftragter - Dashboard Aktionen //5P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#46]
Als Beauftragter eines Fachgebiets möchte ich zusätzlich zu den Aktionen eines regulären Wimi auf meinem Dashboard Links zu Aktionen angezeigt bekommen, um diese häufig wiederkehrenden Tätigkeiten schnell durchzuführen.

**Akzeptanzkriterien**
- [x] Urlaubsanträge einsehen (verlinkt auf: Übersichtsseite mit allen Anträgen, gefiltert nach Urlaubsanträgen, die von den Wimis des Fachgebiets beantragt worden sind, #70)
- [x] Dienstreise-Anträge einsehen (verlinkt auf: Übersichtsseite mit allen Anträgen, gefiltert nach Dienstreise-Anträgen, die von Wimis des Fachgebiets beantragt worden sind, #70) 
- [x] Reisekostenabrechnung-Anträge einsehen (verlinkt auf: Übersichtsseite mit allen Anträgen, gefiltert nach Reisekostenabrechnung-Anträgen, die von Wimis des Fachgebiets beantragt worden sind, #70) 

![capture](https://cloud.githubusercontent.com/assets/9438971/11625315/5ddbf1b2-9cda-11e5-9390-ae59f01e5566.PNG)
