### ISSUE TITLE
Stundenzettel - Als Hiwi einen Stundenzettel zur Bestätigung vorlegen // 2P // 1,5P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#50]
Als Hiwi möchte ich einen Stundenzettel für ein bestimmtes Projekt unterschrieben an meinen zuständigen Wimi übermitteln können, um so problemlos online meinen Stundenzettel abgeben zu können.

**Akzeptanzkriterien**
- [ ] Falls der Hiwi eine Unterschrift im System hinterlegt hat, kann er auf der Seite für die Arbeitsstunden zu einem Monat für ein bestimmtes Projekt "Mit Unterschrift versehen" auswählen und die Bestätigung beantragen. Die anzuzeigende PDF enthält dann die Unterschrift.
- [x] Nach dem Beantragen der Unterschrift kann jeder Wimi des Projekts den Stundenzettel bestätigen/ablehnen.

**Tasks**
- [x] Button zum Unterschrift hinzufügen hinzufügen
- [x] Button zur Bestätigungsanfrage hinzufügen
- [x] Spalte hinzufügen, die den Bestätigungsstand angibt
- [x] Anmerkungstext anzeigen
- [x] Bug fix
- [ ] Rechteverwaltung

![bildschirmfoto 2015-11-24 um 15 36 27](https://cloud.githubusercontent.com/assets/7271491/11369893/6171c46e-92c1-11e5-813f-2bc8147396f9.png)

![bildschirmfoto 2015-11-24 um 22 37 25](https://cloud.githubusercontent.com/assets/7271491/11381381/0f51bc4e-92fc-11e5-8b23-198ae350596a.png)

![bildschirmfoto 2015-11-24 um 15 37 03](https://cloud.githubusercontent.com/assets/7271491/11369996/d409f000-92c1-11e5-90f6-a46f4e5d9db0.png)

**Comment by mandyklingbeil** [comment]
PDF export nach vor nicht möglich. Übernahme in die Kansan-Week
