### ISSUE TITLE
FG-Admin - Fachgebiet - Nutzer entfernen//20P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#52]
Als Admin eines Fachgebiets (FG) kann ich Mitglieder eines Fachgebiets (= Wimis) aus dem Fachgebiet wieder entfernen, um personelle Änderungen am Fachgebiet zu aktualisieren. Dazu gibt es auf der Seite des Fachgebiets einen Link hinter jedem Wimi "Aus Fachgebiet entfernen".

Als Admin eines Fachgebiets kann ich anderen Wimis Administratorenrechte geben, entziehen oder sie aus dem Fachgebiet entfernen. 

**Akzeptanzkriterien**
- [x] Nachdem der Admin einen Wimi über Klick auf "Aus Fachgebiet entfernen" entfernt hat, taucht er nicht mehr in der Liste der Wissenschaftlichen Mitarbeiter auf
- [x] Er verliert zudem alle an seine Rolle geknüpften Privilegien
- [x] Man kann seine eigene Administratorrolle nicht ablegen
- [x] Man kann sich nicht selbst aus dem Fachgebiet entfernen

**Tasks**
- [x] Alle Tasks aus #66 erledigen.
- [x] Admin-Rechte vergeben und entziehen implementieren. (ist eig. #62)
 
Beispielhafte Ansicht (aus Sicht des FG-Beauftragten):
![capture](https://cloud.githubusercontent.com/assets/9438971/11625024/1153288a-9cd8-11e5-9979-a31d99dd766a.PNG)

**Comment by marcelja** [comment]
Kann ein Admin Rechte für FG-Beauftragte geben/entziehen?
Falls nicht, kann das dann nur der Superadmin?

**Comment by mandyklingbeil** [comment]
Nein, das kann nur der Superadmin. Im Wiki gibt es auch eine Übersicht über alle Rollen und darüber, was sie können (und was nicht).
