### ISSUE TITLE
Profil - Verfügbare Urlaubstage eintragen // 5P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#53]
Als Wimi möchte ich eintragen können, wie viele Urlaubstage mir aktuell zur Verfügung stehen. Dazu kann ich in meinem Profil unter Urlaub bei verfügbaren Urlaubstagen auf "Bearbeiten" klicken. Habe ich dies getan, kann ich eintragen, wie viele Urlaubstage mir aus dem vergangenen Jahr und wie viele Urlaubstage mit aus dem aktuellen Jahr zustehen. Nach "Speichern" wird mir die Gesamtzahl meiner verfügbaren Urlaubstage auf dem Profil angezeigt und wie viele davon aus dem Vorjahr übernommen worden sind. Wurden Urlaubstage aus dem Vorjahr übernommen, erscheint bis zum 31.03. ein Hinweis, dass diese am 31.03. verfallen werden. Der Hinweis verschwindet am 1. April. 

**Tasks**
- [x] Urlaubsberechnung verbessern -> Wochenenden/Feiertage nicht mitrechnen 1 Std
- [x] Urlaubsberechnung auf konkretisierte Anforderung umstellen 1 Std
- [x] Datumsabhängigen Warnhinweis einbauen 1 Std
- [x] Urlaubsantrag Übersicht im Profil verbessern 1 Std

**Akzeptanzkriterien**
- [x] Die Zahl meiner Gesamt-Resturlaubstage wird auf dem Profil angezeigt.
- [x] Nach Klick auf "Bearbeiten" der verfügbaren Urlaubstage kann ich die Anzahl der Urlaubstage für das Vorjahr und für das aktuelle Jahr bearbeiten und speichern. 
- [x] Bestehen Resturlaubstage aus dem Vorjahr und befinden wir uns zeitlich zwischen dem 1.1. und dem 31.3., erscheint ein Warnhinweis, dass die Resturlaubstage aus dem Vorjahr verfallen werden.

![bildschirmfoto 2015-11-24 um 22 41 46](https://cloud.githubusercontent.com/assets/7271491/11381476/9b314da6-92fc-11e5-9113-bb566e2a1fa9.png)

![bildschirmfoto 2015-11-24 um 22 25 15](https://cloud.githubusercontent.com/assets/7271491/11381082/484aaa3a-92fa-11e5-852c-51e01e48de21.png)
