### ISSUE TITLE
Wimi - Dienstreise-Antrag bearbeiten und stellen//25P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#58]
Als Wimi möchte ich meine Dienstreiseanträge einzeln im Detail mit allen Daten einsehen können (Status, Dienstreise-Ziel, Start- und Enddatum, Tage, davon Auslandstage, Anmerkungen), egal in welchem Status sie sich befinden (gespeichert, beantragt, genehmigt, abgelehnt), um verschiedene Aktionen vornehmen zu können. Ist ein Antrag gespeichert, kann ich den Antrag in allen Punkten bearbeiten und ihn anzeigen/drucken oder stellen. Ist ein Antrag bereits beantragt, aber noch nicht genehmigt, kann ich den Antrag rückgängig machen. Ist der Antrag bereits beantragt und genehmigt/als formal korrekt markiert (**Ticket folgt**)/abgelehnt, wird mir angezeigt, wer diese Aktion vorgenommen hat. Dann kann ich nur noch die PDF anzeigen lassen. 

**Akzeptanzkriterien**
- [x] Ein gespeicherter Dienstreiseantrag kann gestellt werden, wodurch der Beauftragte des Fachgebiets  Zugriff darauf erhält.
- [x] Hat ein Wimi einen Dienstreise-Antrag gespeichert, kann er den Antrag bearbeiten.
- [x] Ein gestellter Antrag kann dann nicht mehr bearbeitet werden
- [x] Nach dem Speichern des Dienstreiseantrags lande ich auf der Detailseite von diesem.

**Tasks**
- [x] view test anpassen
- [x] status zum Model Trip hinzufügen
- [x] je nach status buttons im view anzeigen

![capture](https://cloud.githubusercontent.com/assets/9438971/11747391/520af602-a023-11e5-8f33-180ae987169c.PNG)
![capture](https://cloud.githubusercontent.com/assets/9438971/11747409/643624a0-a023-11e5-9958-6e79f0a2c073.PNG)
