### ISSUE TITLE
HiWi - Arbeitsstunden für ein bestimmtes Projekt eintragen // 5P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#59]
Als HiWi möchte ich meine Arbeitsstunden für den monatlichen Stundenzettel projektspezifisch festhalten, um bei mehreren Anstellungen verschiedene Stundenzettel erzeugen zu können.

In meinem Profil sehe ich dafür unter "Arbeitsstunden" die jeweiligen Monate. Der letzte Monate ist derjenige, in dem ich mich beim Wimi Portal registriert habe. Hinter dem jeweiligen Monat werden alle Projekte namentlich aufgeführt, bei denen ich zum Zeitpunkt des Monats als Hiwi eingetragen war. Der Name ist verlinkt und führt auf eine neue Seite, auf der ich alle Arbeitsstunden, die zu diesem Projekt in dem entsprechenden Monat gehören, einsehen kann. 

Auf der Seite der Arbeitsstunden für ein bestimmtes Projekt für einen bestimmten Monat kann ich außerdem eintragen, für wie viele Stunden ich für diesen Monat eingestellt bin/war und wie viel Gehalt ich erhalte. Stunden können sowohl pro Woche als auch pro Monat eingetragen werden. Das Gehalt kann sowohl pro Stunde als auch pro Monat eingetragen werden. Beide Angaben sind optional anzugeben.

**Tasks**
- [x] Relation von Stundenzettel zu Projekt herstellen
- [x] Parameter für Projekt in Stundenzettel View einbeziehen
- [x] Eingabe für Gehalt hinzufügen
- [x] Monatsgehalt und planmäßige Arbeitsstunden auf View anzeigen
- [ ] Datepicker benutzen wenn daten ausgewählt werden sollen

**Akzeptanzkriterien**
- [x] Auf meinem Profil gibt es unter "Arbeitsstunden" einen Link zu der Übersicht der Arbeitsstunden zu einem bestimmten Projekt, dem ich zugeordnet bin.
- [x] Auf der Übersicht der Arbeitsstunden gibt es zwei Einträge für Arbeitszeit und Gehalt, die ich über einen Link oder Button bearbeiten kann. 

![bildschirmfoto 2015-11-24 um 15 35 31](https://cloud.githubusercontent.com/assets/7271491/11369883/5588e254-92c1-11e5-9a33-55bb69b524d7.png)

![bildschirmfoto 2015-11-24 um 20 48 57](https://cloud.githubusercontent.com/assets/7271491/11378711/dc245f66-92ec-11e5-9540-abe98cc43038.png)

![bildschirmfoto 2015-11-25 um 09 37 01](https://cloud.githubusercontent.com/assets/7271491/11392161/2252054a-9358-11e5-8df9-d0d05fa263ec.png)

![bildschirmfoto 2015-11-25 um 09 39 40](https://cloud.githubusercontent.com/assets/7271491/11392210/795561b6-9358-11e5-96de-d3926761a579.png)

**Comment by threxx** [comment]
@Sephor wie weit bist du denn mit den Stundenzettel? Ist es schon möglich alle Stundenzettel einzusehen und die von einer bestimmten Person? Gibt es dazu einen Pfad?

**Comment by Sephor** [comment]
@threxx wofür brauchst du es denn?

**Comment by threxx** [comment]
meine User Story (#43) ist indirekt davon abhängig, da ich eine Verlinkung zu allen Stundenzettel eine Projektes und jedes Hiwis machen soll.

**Comment by Sephor** [comment]
@threxx Es gibt im Moment keine Übersicht aller Stundenzettel eines Hiwis im Projekt, weil der Hiwi die auf seiner Profilseite stehen hat. Man könnte aber eine solche Übersicht auf der time_sheet/index Seite machen.

**Comment by mandyklingbeil** [comment]
@threxx: Das wäre vermutlich die Übersicht, die für #47 angelegt werden muss.

**Comment by threxx** [comment]
@mandyklingbeil okay gut zu wissen bei #43 wurde nur #59 verlinkt.

**Comment by Sephor** [comment]
@threxx Ok also der Issue ist noch niemandem assigned, dann wird es auch schwierig dahin zu verlinken.

**Comment by threxx** [comment]
@Sephor naja wäre ja egal. Ich muss mit meinem issue sowieso warten, aber du das ja gar nicht machst, was in meinem issue verlinkt ist, dann wäre es ja nur richtig, das auf den richtigen issue zu verlinken.

**Comment by threxx** [comment]
@Sephor @sleighsoft Das ist noch nicht im dev oder? Wann habt ihr denn vor, das in den dev zu mergen?
