### ISSUE TITLE
FG-Admin - Fachgebiet - Mitgliedschaft bestätigen//5P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#66]
Als Admin eines Fachgebiets (FG) kann ich Anfragen auf Mitgliedschaft für das Fachgebiet bestätigen oder ablehnen. Bestätige ich eine Anfrage, wird der Anfragende dem Fachgebiet zugeordnet und erhält den Status Wimi. Nach Ablehnung verschwindet die Anfrage von der Seite.

**Akzeptanzkriterien**
- [x] Auf der FG-Seite kann ein Admin des FGs Mitgliedschaften bestätigen oder ablehnen. Nach Bestätigung einer Mitgliedschaft ist der Anfragende ein Wimi des Fachgebiets.

**Tasks**
- [x] 'chair_wimi' Tabelle erstellen, die Wimis zu Fachgebieten zuordnet.
- [x] View für Admins / FG-Beauftragte erstellen.
- [x] Chair-View für Users erstellen: 'Apply as Wimi'-Button für jeden Lehrstuhl

Beispielhafte Ansicht (eines FG-Beauftragten):
![capture](https://cloud.githubusercontent.com/assets/9438971/11625024/1153288a-9cd8-11e5-9979-a31d99dd766a.PNG)
