### ISSUE TITLE
FG-Beauftragter - Übersicht über Anträge//10P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#70]
Als FG-Beauftragter möchte ich schnell Einsicht in die Anträge meiner Wimis und Hiwis kommen. Dazu gibt es eine Übersicht über alle Anträge, die im Fachgebiet eingereicht worden sind. Diese Seite erreiche ich von meinem Dashboard aus (#46).

**Akzeptanzkriterien**
- [x] Es werden alle Anträge zu einem Fachgebiet dem FG-Beauftragten auf einer Seite angezeigt.
- [x] Auf der Seite kann der FG-Beauftragte filtern nach Antragsart und Status.
- [x] Es gibt einen Link auf dem Dashboard
- [x] Anträge sind absteigend nach Datum sortiert (mit den neusten Anträgen ganz oben)

**Tasks**
- [x] RequestController erstellen   
- [x] Filter mit JS erstellen
- [x] Views anpassen
- [x] Tests

![bildschirmfoto 2015-11-25 um 11 03 16](https://cloud.githubusercontent.com/assets/7271491/11394247/29817ec0-9364-11e5-9df9-199fd80b39d1.png)
